import React, { useEffect, useState } from 'react';
import { adminAPI } from '../services/api';
import { FiPlus, FiRefreshCw } from 'react-icons/fi';

export default function GraceOffersPage() {
  const [policies, setPolicies] = useState([]); const [plans, setPlans] = useState([]); const [show, setShow] = useState(false);
  const [form, setForm] = useState({ name: 'New driver grace offer', plan_id: '', start_at: '', end_at: '', duration_days: 7, apply_to_new_drivers: true, apply_to_existing: false, is_active: true });
  const load = () => adminAPI.gracePolicies().then(({ data }) => setPolicies(data.data || []));
  useEffect(() => { load(); fetch('/api/subscription-plans').then(r => r.json()).then(d => setPlans(d.data || [])); }, []);
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));
  const save = async () => { await adminAPI.gracePolicyCreate(form); setShow(false); load(); };
  const edit = async (p) => { const duration = window.prompt('Grace duration in days', p.duration_days); if (duration === null) return; await adminAPI.gracePolicyUpdate(p.id, { duration_days: Number(duration), is_active: !p.is_active }); load(); };
  return <div className="page-subscriptions"><div className="page-toolbar"><div><h1>Driver Grace Offers</h1><p className="muted">Configure and adjust automatic driver package offers at any time.</p></div><button className="btn btn-sm" onClick={load}><FiRefreshCw /> Refresh</button><button className="btn btn-sm btn-accent" onClick={() => setShow(true)}><FiPlus /> New offer</button></div>
    {show && <div className="content-card" style={{ marginBottom: 18 }}><h2>Create grace offer</h2><div className="form-grid"><input className="d-input" placeholder="Offer name" value={form.name} onChange={e => set('name', e.target.value)} /><select className="d-input" value={form.plan_id} onChange={e => set('plan_id', e.target.value)}><option value="">Select package</option>{plans.map(p => <option key={p.id} value={p.id}>{p.name} ({p.period})</option>)}</select><input className="d-input" type="datetime-local" value={form.start_at} onChange={e => set('start_at', e.target.value)} /><input className="d-input" type="datetime-local" value={form.end_at} onChange={e => set('end_at', e.target.value)} /><input className="d-input" type="number" min="1" value={form.duration_days} onChange={e => set('duration_days', e.target.value)} /></div><p><label><input type="checkbox" checked={form.apply_to_new_drivers} onChange={e => set('apply_to_new_drivers', e.target.checked)} /> New drivers</label> <label><input type="checkbox" checked={form.apply_to_existing} onChange={e => set('apply_to_existing', e.target.checked)} /> Existing pending drivers</label></p><button className="btn btn-sm btn-accent" onClick={save}>Save offer</button> <button className="btn btn-sm" onClick={() => setShow(false)}>Cancel</button></div>}
    <div className="content-card"><table><thead><tr><th>Offer</th><th>Package</th><th>Window</th><th>Duration</th><th>Audience</th><th>Status</th><th>Adjust</th></tr></thead><tbody>{policies.map(p => <tr key={p.id}><td>{p.name}</td><td>{p.plan?.name || '—'}</td><td>{new Date(p.start_at).toLocaleString()} – {new Date(p.end_at).toLocaleString()}</td><td>{p.duration_days} days</td><td>{[p.apply_to_new_drivers && 'New', p.apply_to_existing && 'Existing'].filter(Boolean).join(', ')}</td><td>{p.is_active ? 'Active' : 'Inactive'}</td><td><button className="btn btn-xs" onClick={() => edit(p)}>Adjust</button></td></tr>)}</tbody></table>{!policies.length && <p className="empty-state">No grace offers configured.</p>}</div>
  </div>;
}
